/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCliente;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author Cesar
 */
public class Reservaciones extends javax.swing.JFrame {

    /**
     * Creates new form Reservaciones
     */
    public Reservaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdConfirmacion = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReservaciones = new javax.swing.JButton();
        lblMesa = new javax.swing.JLabel();
        cbxTam = new javax.swing.JComboBox<>();
        cbxUbicacion = new javax.swing.JComboBox<>();
        cbxColocacion = new javax.swing.JComboBox<>();
        lblEvento = new javax.swing.JLabel();
        lblReservaciones = new javax.swing.JLabel();
        cbxEvento = new javax.swing.JComboBox<>();
        cbxMes = new javax.swing.JComboBox<>();
        lblOtros = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtOtros = new javax.swing.JTextField();
        cbxDia = new javax.swing.JComboBox<>();
        cbxAño = new javax.swing.JComboBox<>();

        jdConfirmacion.setMaximumSize(new java.awt.Dimension(300, 100));
        jdConfirmacion.setMinimumSize(new java.awt.Dimension(300, 100));
        jdConfirmacion.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Su reservacion fue exitosa");

        javax.swing.GroupLayout jdConfirmacionLayout = new javax.swing.GroupLayout(jdConfirmacion.getContentPane());
        jdConfirmacion.getContentPane().setLayout(jdConfirmacionLayout);
        jdConfirmacionLayout.setHorizontalGroup(
            jdConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdConfirmacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jdConfirmacionLayout.setVerticalGroup(
            jdConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdConfirmacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        btnReservaciones.setBackground(new java.awt.Color(255, 255, 153));
        btnReservaciones.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnReservaciones.setText("Realizar Reservación");

        lblMesa.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lblMesa.setForeground(new java.awt.Color(255, 255, 153));
        lblMesa.setText("Mesa");

        cbxTam.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxTam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tam", "1", "2", "3", "4", "5", "6" }));

        cbxUbicacion.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ubicación", "Balcon", "Ventana", "Salon" }));

        cbxColocacion.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxColocacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colocación", "Izquierda", "Centro", "Derecha" }));

        lblEvento.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(255, 255, 153));
        lblEvento.setText("¿Evento en especial?");

        lblReservaciones.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblReservaciones.setForeground(new java.awt.Color(255, 255, 153));
        lblReservaciones.setText("Reservaciones");

        cbxEvento.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cumpleaños", "Romance", "Reuniones", " ", " " }));

        cbxMes.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febre", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agost", "Septi", "Octub", "Novie", "Dicie" }));

        lblOtros.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lblOtros.setForeground(new java.awt.Color(255, 255, 153));
        lblOtros.setText("Otros:");

        lblFecha.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 153));
        lblFecha.setText("Selecionar la fecha");

        txtOtros.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        cbxDia.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxAño.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020", "2021", "2022" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(cbxTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxColocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOtros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEvento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnReservaciones))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFecha)
                            .addComponent(lblMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblReservaciones)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblReservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxColocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEvento)
                .addGap(15, 15, 15)
                .addComponent(cbxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtros))
                .addGap(41, 41, 41)
                .addComponent(btnReservaciones)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservaciones().setVisible(true);
            }
        });
    }

    public JButton getBtnReservaciones() {
        return btnReservaciones;
    }

    public void setBtnReservaciones(JButton btnReservaciones) {
        this.btnReservaciones = btnReservaciones;
    }

    public JComboBox<String> getCbxAño() {
        return cbxAño;
    }

    public void setCbxAño(JComboBox<String> cbxAño) {
        this.cbxAño = cbxAño;
    }

    public JComboBox<String> getCbxColocacion() {
        return cbxColocacion;
    }

    public void setCbxColocacion(JComboBox<String> cbxColocacion) {
        this.cbxColocacion = cbxColocacion;
    }

    public JComboBox<String> getCbxDia() {
        return cbxDia;
    }

    public void setCbxDia(JComboBox<String> cbxDia) {
        this.cbxDia = cbxDia;
    }

    public JComboBox<String> getCbxEvento() {
        return cbxEvento;
    }

    public void setCbxEvento(JComboBox<String> cbxEvento) {
        this.cbxEvento = cbxEvento;
    }

    public JComboBox<String> getCbxMes() {
        return cbxMes;
    }

    public void setCbxMes(JComboBox<String> cbxMes) {
        this.cbxMes = cbxMes;
    }

    public JComboBox<String> getCbxTam() {
        return cbxTam;
    }

    public void setCbxTam(JComboBox<String> cbxTam) {
        this.cbxTam = cbxTam;
    }

    public JComboBox<String> getCbxUbicacion() {
        return cbxUbicacion;
    }

    public void setCbxUbicacion(JComboBox<String> cbxUbicacion) {
        this.cbxUbicacion = cbxUbicacion;
    }

    public JTextField getTxtOtros() {
        return txtOtros;
    }

    public void setTxtOtros(JTextField txtOtros) {
        this.txtOtros = txtOtros;
    }

    public JDialog getJdConfirmacion() {
        return jdConfirmacion;
    }

    public void setJdConfirmacion(JDialog jdConfirmacion) {
        this.jdConfirmacion = jdConfirmacion;
    }


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservaciones;
    private javax.swing.JComboBox<String> cbxAño;
    private javax.swing.JComboBox<String> cbxColocacion;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxEvento;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JComboBox<String> cbxTam;
    private javax.swing.JComboBox<String> cbxUbicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog jdConfirmacion;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblOtros;
    private javax.swing.JLabel lblReservaciones;
    private javax.swing.JTextField txtOtros;
    // End of variables declaration//GEN-END:variables
}
