/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaAdmin;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Cesar
 */
public class Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaPedido1 = new javax.swing.JTextArea();
        lblMesa1 = new javax.swing.JLabel();
        lblMesa3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaPedido3 = new javax.swing.JTextArea();
        lblMesa5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaPedido5 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaPedido2 = new javax.swing.JTextArea();
        btnPedido1 = new javax.swing.JButton();
        btnPedido3 = new javax.swing.JButton();
        btnPedido5 = new javax.swing.JButton();
        lblMesa2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaPedido4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaPedido6 = new javax.swing.JTextArea();
        btnPedido2 = new javax.swing.JButton();
        lblMesa4 = new javax.swing.JLabel();
        lblMesa6 = new javax.swing.JLabel();
        btnPedido4 = new javax.swing.JButton();
        btnPedido6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDomicilios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDomicilio = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 500));

        lblMesas.setText("Atención a Mesas");

        txtaPedido1.setColumns(1);
        txtaPedido1.setRows(5);
        jScrollPane1.setViewportView(txtaPedido1);

        lblMesa1.setText("Pedido1");

        lblMesa3.setText("Pedido3");

        txtaPedido3.setColumns(20);
        txtaPedido3.setRows(5);
        jScrollPane3.setViewportView(txtaPedido3);

        lblMesa5.setText("Pedido5");

        txtaPedido5.setColumns(20);
        txtaPedido5.setRows(5);
        jScrollPane4.setViewportView(txtaPedido5);

        txtaPedido2.setColumns(20);
        txtaPedido2.setRows(5);
        jScrollPane5.setViewportView(txtaPedido2);

        btnPedido1.setText("Entregado");

        btnPedido3.setText("Entregado");

        btnPedido5.setText("Entregado");

        lblMesa2.setText("Pedido2");

        txtaPedido4.setColumns(20);
        txtaPedido4.setRows(5);
        jScrollPane6.setViewportView(txtaPedido4);

        txtaPedido6.setColumns(20);
        txtaPedido6.setRows(5);
        jScrollPane7.setViewportView(txtaPedido6);

        btnPedido2.setText("Entregado");

        lblMesa4.setText("Pedido4");

        lblMesa6.setText("Pedido6");

        btnPedido4.setText("Entregado");

        btnPedido6.setText("Entregado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPedido1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMesa5)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane1)
                                    .addComponent(lblMesa3))
                                .addComponent(btnPedido3)
                                .addComponent(btnPedido5))
                            .addComponent(lblMesa1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMesa2)
                                    .addComponent(lblMesa4)
                                    .addComponent(lblMesa6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPedido2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPedido4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPedido6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMesas)
                        .addGap(248, 248, 248)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesa1)
                    .addComponent(lblMesa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido1)
                    .addComponent(btnPedido2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesa3)
                    .addComponent(lblMesa4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido3)
                    .addComponent(btnPedido4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesa5)
                    .addComponent(lblMesa6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido5)
                    .addComponent(btnPedido6))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 500));

        lblDomicilios.setText("Domicilios");

        txtaDomicilio.setColumns(20);
        txtaDomicilio.setRows(5);
        jScrollPane2.setViewportView(txtaDomicilio);

        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblDomicilios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblDomicilios)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    public JLabel getLblMesa1() {
        return lblMesa1;
    }

    public void setLblMesa1(JLabel lblMesa1) {
        this.lblMesa1 = lblMesa1;
    }

    public JButton getBtnPedido1() {
        return btnPedido1;
    }

    public void setBtnPedido1(JButton btnPedido1) {
        this.btnPedido1 = btnPedido1;
    }

    public JButton getBtnPedido2() {
        return btnPedido2;
    }

    public void setBtnPedido2(JButton btnPedido2) {
        this.btnPedido2 = btnPedido2;
    }

    public JButton getBtnPedido3() {
        return btnPedido3;
    }

    public void setBtnPedido3(JButton btnPedido3) {
        this.btnPedido3 = btnPedido3;
    }

    public JButton getBtnPedido4() {
        return btnPedido4;
    }

    public void setBtnPedido4(JButton btnPedido4) {
        this.btnPedido4 = btnPedido4;
    }

    public JButton getBtnPedido5() {
        return btnPedido5;
    }

    public void setBtnPedido5(JButton btnPedido5) {
        this.btnPedido5 = btnPedido5;
    }

    public JButton getBtnPedido6() {
        return btnPedido6;
    }

    public void setBtnPedido6(JButton btnPedido6) {
        this.btnPedido6 = btnPedido6;
    }

    public JTextArea getTxtaPedido1() {
        return txtaPedido1;
    }

    public void setTxtaPedido1(JTextArea txtaPedido1) {
        this.txtaPedido1 = txtaPedido1;
    }

    public JTextArea getTxtaPedido2() {
        return txtaPedido2;
    }

    public void setTxtaPedido2(JTextArea txtaPedido2) {
        this.txtaPedido2 = txtaPedido2;
    }

    public JTextArea getTxtaPedido3() {
        return txtaPedido3;
    }

    public void setTxtaPedido3(JTextArea txtaPedido3) {
        this.txtaPedido3 = txtaPedido3;
    }

    public JTextArea getTxtaPedido4() {
        return txtaPedido4;
    }

    public void setTxtaPedido4(JTextArea txtaPedido4) {
        this.txtaPedido4 = txtaPedido4;
    }

    public JTextArea getTxtaPedido5() {
        return txtaPedido5;
    }

    public void setTxtaPedido5(JTextArea txtaPedido5) {
        this.txtaPedido5 = txtaPedido5;
    }

    public JTextArea getTxtaPedido6() {
        return txtaPedido6;
    }

    public void setTxtaPedido6(JTextArea txtaPedido6) {
        this.txtaPedido6 = txtaPedido6;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido1;
    private javax.swing.JButton btnPedido2;
    private javax.swing.JButton btnPedido3;
    private javax.swing.JButton btnPedido4;
    private javax.swing.JButton btnPedido5;
    private javax.swing.JButton btnPedido6;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblDomicilios;
    private javax.swing.JLabel lblMesa1;
    private javax.swing.JLabel lblMesa2;
    private javax.swing.JLabel lblMesa3;
    private javax.swing.JLabel lblMesa4;
    private javax.swing.JLabel lblMesa5;
    private javax.swing.JLabel lblMesa6;
    private javax.swing.JLabel lblMesas;
    private javax.swing.JTextArea txtaDomicilio;
    private javax.swing.JTextArea txtaPedido1;
    private javax.swing.JTextArea txtaPedido2;
    private javax.swing.JTextArea txtaPedido3;
    private javax.swing.JTextArea txtaPedido4;
    private javax.swing.JTextArea txtaPedido5;
    private javax.swing.JTextArea txtaPedido6;
    // End of variables declaration//GEN-END:variables
}
